/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api.test.framework.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        assertEquals("Hello World!", "Hello World!");
    }
    @Test void testGetMessage2() {
        assertEquals("Hello World!", "Hello World!");
    }
}
