/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api.test.framework.app;

public class App {
    public static void main(String[] args) {

        System.out.println("Hello world!!!");
    }
}
